export const orderBumpsDataTemplate = {
  orderBumpsMetrics: {
    totalOffers: 0,
    activeOffers: 0,
    totalRevenue: 0,
    conversionRate: 0,
    averageOrderValue: 0,
    averageOrderValueWithoutBumps: 0,
    uplift: 0,
    totalOrders: 0,
    ordersWithBumps: 0,
    bumpsRevenue: 0,
    bumpsPercentageOfTotal: 0,
  },
  orderBumpsPerformance: [
    {
      id: 0,
      name: '',
      product: '',
      price: 0,
      impressions: 0,
      conversions: 0,
      conversionRate: 0,
      revenue: 0,
      position: '',
      status: '',
      category: '',
    },
  ],
  orderBumpsEvolution: [
    {
      date: '',
      conversions: 0,
      revenue: 0,
      conversionRate: 0,
    },
  ],
  performanceComparison: {
    withOrderBumps: {
      averageOrderValue: 0,
      conversionRate: 0,
      totalRevenue: 0,
      customerLifetimeValue: 0,
      refundRate: 0,
    },
    withoutOrderBumps: {
      averageOrderValue: 0,
      conversionRate: 0,
      totalRevenue: 0,
      customerLifetimeValue: 0,
      refundRate: 0,
    },
    improvement: {
      averageOrderValue: 0,
      totalRevenue: 0,
      customerLifetimeValue: 0,
      refundRate: 0,
    },
  },
  categoryAnalysis: [
    {
      category: '',
      offers: 0,
      averagePrice: 0,
      conversionRate: 0,
      totalRevenue: 0,
      description: '',
    },
  ],
  orderBumpsInsights: [
    {
      id: 0,
      type: '',
      title: '',
      description: '',
      confidence: 0,
      impact: '',
      action: '',
      potentialRevenue: 0,
      priority: '',
    },
  ],
  abTestData: [
    {
      id: 0,
      name: '',
      variant: '',
      price: 0,
      conversions: 0,
      impressions: 0,
      conversionRate: 0,
      revenue: 0,
      status: '',
    },
  ],
  orderBumpsByProduct: [
    {
      productName: '',
      productRevenue: 0,
      orderBumpsRevenue: 0,
      orderBumpsCount: 0,
      averageUplift: 0,
      topOrderBump: '',
    },
  ],
  orderBumpsHourlyPerformance: [
    {
      hour: '',
      conversions: 0,
      conversionRate: 0,
    },
  ],
  industryBenchmarks: {
    averageConversionRate: 0,
    averageUplift: 0,
    averageOrderBumpsPerProduct: 0,
    topPerformingCategories: [''],
    recommendedPriceRange: {
      min: 0,
      max: 0,
      optimal: 0,
    },
  },
};
