export const productsDataTemplate = {
  productsOverview: {
    totalProducts: 0,
    activeProducts: 0,
    draftProducts: 0,
    archivedProducts: 0,
    totalRevenue: 0,
    avgPrice: 0,
    totalSales: 0,
    conversionRate: 0,
  },
  productsList: [
    {
      id: 0,
      name: '',
      type: '',
      category: '',
      price: 0,
      status: '',
      sales: 0,
      revenue: 0,
      conversion: 0,
      growth: 0,
      rating: 0,
      reviews: 0,
      createdAt: '',
      lastSale: '',
      description: '',
      tags: [''],
      thumbnail: '',
      commission: 0,
      refundRate: 0,
      avgTimeToSale: 0,
      customerSatisfaction: 0,
    },
  ],
  productCategories: [
    {
      name: '',
      count: 0,
      revenue: 0,
      growth: 0,
    },
  ],
  productPerformanceData: [
    {
      month: '',
      products: 0,
      sales: 0,
      revenue: 0,
    },
  ],
  productInsights: [
    {
      id: 0,
      type: '',
      title: '',
      description: '',
      confidence: 0,
      impact: '',
      potentialRevenue: 0,
      action: '',
      priority: '',
    },
  ],
  productGoals: [
    {
      id: 0,
      title: '',
      current: 0,
      target: 0,
      progress: 0,
      deadline: '',
      status: '',
      description: '',
    },
  ],
  topSellingProducts: [
    {
      id: 0,
      name: '',
      type: '',
      category: '',
      price: 0,
      status: '',
      sales: 0,
      revenue: 0,
      conversion: 0,
      growth: 0,
      rating: 0,
      reviews: 0,
      createdAt: '',
      lastSale: '',
      description: '',
      tags: [''],
      thumbnail: '',
      commission: 0,
      refundRate: 0,
      avgTimeToSale: 0,
      customerSatisfaction: 0,
    },
  ],
  productTypeDistribution: [
    {
      type: '',
      count: 0,
      revenue: 0,
      percentage: 0,
    },
  ],
};
