export const salesDataTemplate = {
  salesMetrics: {
    totalRevenue: 0,
    totalOrders: 0,
    averageOrderValue: 0,
    conversionRate: 0,
    refundRate: 0,
    customerLifetimeValue: 0,
    newCustomers: 0,
    returningCustomers: 0,
    grossMargin: 0,
    netMargin: 0,
  },
  salesEvolution: [
    {
      date: '',
      revenue: 0,
      orders: 0,
      aov: 0,
      conversion: 0,
    },
  ],
  productSalesAnalysis: [
    {
      id: 0,
      name: '',
      category: '',
      price: 0,
      revenue: 0,
      orders: 0,
      conversionRate: 0,
      refundRate: 0,
      averageRating: 0,
      totalReviews: 0,
      launchDate: '',
      status: '',
      growth: 0,
      margin: 0,
      customerSatisfaction: 0,
      repeatPurchaseRate: 0,
      affiliateCommission: 0,
      trafficSources: {
        organic: 0,
        facebook: 0,
        google: 0,
        instagram: 0,
        email: 0,
      },
    },
  ],
  salesFunnel: [
    {
      stage: '',
      count: 0,
      percentage: 0,
      conversionToNext: 0,
      averageTimeSpent: '',
      bounceRate: 0,
      topSources: [''],
    },
  ],
  salesChannels: [
    {
      channel: '',
      revenue: 0,
      orders: 0,
      conversionRate: 0,
      averageOrderValue: 0,
      cost: 0,
      roi: 0,
      customerAcquisitionCost: 0,
      lifetimeValue: 0,
      growth: 0,
    },
  ],
  hourlyAnalysis: [
    {
      hour: '',
      revenue: 0,
      orders: 0,
      conversion: 0,
    },
  ],
  cohortAnalysis: [
    {
      cohort: '',
      month0: 0,
      month1: 0,
      month2: 0,
      month3: 0,
      month4: 0,
      month5: 0,
      month6: 0,
      totalRevenue: 0,
      averageLTV: 0,
    },
  ],
  salesInsights: [
    {
      id: 0,
      type: '',
      title: '',
      description: '',
      confidence: 0,
      impact: '',
      action: '',
      potentialRevenue: 0,
      priority: '',
      category: '',
    },
  ],
  salesGoals: [
    {
      id: 0,
      title: '',
      target: 0,
      current: 0,
      progress: 0,
      deadline: '',
      daysRemaining: 0,
      status: '',
      category: '',
    },
  ],
  cartAbandonmentAnalysis: {
    totalAbandoned: 0,
    abandonmentRate: 0,
    recoveredCarts: 0,
    recoveryRate: 0,
    lostRevenue: 0,
    recoveredRevenue: 0,
    averageTimeToAbandon: '',
    topReasons: [
      {
        reason: '',
        percentage: 0,
      },
    ],
    recoveryStrategies: [
      {
        strategy: '',
        effectiveness: 0,
        revenue: 0,
      },
    ],
  },
  refundAnalysis: {
    totalRefunds: 0,
    refundRate: 0,
    refundedAmount: 0,
    averageRefundTime: '',
    topReasons: [
      {
        reason: '',
        percentage: 0,
      },
    ],
    refundsByProduct: [
      {
        product: '',
        refunds: 0,
        rate: 0,
      },
    ],
  },
  salesBenchmarks: {
    conversionRate: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
    averageOrderValue: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
    customerAcquisitionCost: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
    customerLifetimeValue: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
    refundRate: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
    emailOpenRate: {
      yours: 0,
      industry: 0,
      topPerformers: 0,
    },
  },
};
